import { useState } from 'react';
import {
  ChatCircleIcon,
  CubeIcon,
  LightningIcon,
  TerminalIcon,
} from '@phosphor-icons/react/dist/ssr';

import { Alert } from '../components/Alert.js';
import { Badge } from '../components/Badge.js';
import { Card } from '../components/Card.js';
import { CodeBlock } from '../components/CodeBlock.js';
import { Heading } from '../components/Heading/Heading.js';
import { Select } from '../components/Select.js';
import { bucketKey, type RagBucket } from './RagPipelineBucketsTab.js';

const ALL_BUCKETS_VALUE = '__all__';

// ---------------------------------------------------------------------------
// ModelsTab — read-only Fil-One-managed model (no BYO / no API keys)
// ---------------------------------------------------------------------------

function ModelCard({
  icon,
  heading,
  description,
  testId,
}: {
  icon: React.ReactNode;
  heading: string;
  description: string;
  testId: string;
}) {
  return (
    <Card data-testid={testId} padding="md">
      <div className="space-y-5">
        <div>
          <div className="flex items-center gap-2">
            <span className="text-zinc-400">{icon}</span>
            <span className="text-sm font-semibold text-zinc-800">{heading}</span>
          </div>
          <p className="mt-1 text-xs text-zinc-500">{description}</p>
        </div>
        <div className="rounded-lg border border-zinc-200 bg-zinc-50 p-4">
          <p className="mb-1.5 text-[10px] font-semibold uppercase tracking-widest text-zinc-400">
            Model
          </p>
          <div className="flex items-center justify-between gap-3">
            <span className="text-sm font-medium text-zinc-800">Fil One-managed model</span>
            <Badge color="grey" size="sm" strength="subtle">
              Managed
            </Badge>
          </div>
          <p className="mt-2 text-xs text-zinc-500">
            Embeddings and answers are generated by Fil One's managed model. Bring-your-own model
            support is coming soon.
          </p>
        </div>
      </div>
    </Card>
  );
}

export function ModelsTab({ enabled }: { enabled: boolean }) {
  return (
    <div data-testid="models-tab" className="space-y-6">
      <Heading
        tag="h2"
        size="lg"
        description="Configure the models used for indexing and querying your buckets."
      >
        Models
      </Heading>
      <div className={`grid grid-cols-2 gap-6${!enabled ? ' opacity-60' : ''}`}>
        <ModelCard
          testId="model-card-index"
          icon={<CubeIcon size={16} />}
          heading="Index model"
          description="Creates embeddings when files are uploaded to your buckets."
        />
        <ModelCard
          testId="model-card-query"
          icon={<ChatCircleIcon size={16} />}
          heading="Query model"
          description="Generates answers when you search across your indexed buckets."
        />
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// IntegrateTab
// ---------------------------------------------------------------------------

export function IntegrateTab({ enabled, buckets }: { enabled: boolean; buckets: RagBucket[] }) {
  const enabledBuckets = buckets.filter((b) => b.enabled);
  const [selected, setSelected] = useState<string>(ALL_BUCKETS_VALUE);
  const selectedBucket = enabledBuckets.find((b) => bucketKey(b) === selected);
  const arg = selectedBucket ? selectedBucket.name : '{bucketName}';
  // Bucket names are region-scoped, so the query endpoint needs the region.
  const region = selectedBucket?.region ?? '{region}';

  const mcpCode = JSON.stringify(
    {
      mcpServers: {
        filone: {
          command: 'npx',
          args: ['@filone/mcp-server', '--buckets', arg],
          env: { FILONE_KEY: 'sk-live_...' },
        },
      },
    },
    null,
    2,
  );

  const queryCode = `POST /api/buckets/${arg}/query?region=${region}\n${JSON.stringify({ query: 'What are the retention policies?', top_k: 5 }, null, 2)}`;

  return (
    <div data-testid="integrate-tab" className="space-y-6">
      <div className="flex items-start justify-between gap-4">
        <Heading
          tag="h2"
          size="lg"
          description="Connect your buckets to AI apps and your own code."
        >
          Integrate
        </Heading>
        {enabled && enabledBuckets.length > 0 && (
          <div className="mt-1 flex flex-shrink-0 items-center gap-3">
            <span className="flex-shrink-0 text-xs font-medium text-zinc-400">Select bucket</span>
            <div data-testid="integrate-bucket-select" className="w-44">
              <Select value={selected} onChange={setSelected} aria-label="Select bucket">
                <option value={ALL_BUCKETS_VALUE}>All buckets</option>
                {enabledBuckets.map((b) => (
                  <option key={bucketKey(b)} value={bucketKey(b)}>
                    {b.name}
                  </option>
                ))}
              </Select>
            </div>
          </div>
        )}
      </div>
      {!enabled && (
        <Alert
          variant="grey"
          description="These endpoints will be active once you enable RAG Pipeline on a bucket."
        />
      )}
      <div className="grid grid-cols-2 divide-x divide-zinc-100">
        <div data-testid="integrate-query-api" className="pr-6">
          <div className="flex items-center gap-2">
            <LightningIcon size={16} className="text-zinc-400" />
            <span className="text-sm font-semibold text-zinc-800">Query API</span>
          </div>
          <p className="mt-1 text-xs text-zinc-500">Call directly from your app or agent.</p>
          <div className={`mt-4${!enabled ? ' pointer-events-none select-none blur-md' : ''}`}>
            <CodeBlock code={queryCode} language="bash" />
          </div>
        </div>
        <div data-testid="integrate-mcp" className="pl-6">
          <div className="flex items-center gap-2">
            <TerminalIcon size={16} className="text-zinc-400" />
            <span className="text-sm font-semibold text-zinc-800">MCP endpoint</span>
            <Badge color="grey" size="sm" strength="subtle">
              Coming later
            </Badge>
          </div>
          <p className="mt-1 text-xs text-zinc-500">
            For Claude Desktop, Cursor, and any MCP-compatible client.
          </p>
          <div className="pointer-events-none mt-4 select-none opacity-50">
            <CodeBlock code={mcpCode} language="json" />
          </div>
        </div>
      </div>
    </div>
  );
}
