// Whether a Stripe event still describes the objects the stored billing row
// names.
//
// Stripe delivers and retries out of order, so an event about a subscription or
// a customer the account has already replaced can arrive after the replacement
// is live. Every destructive writer asks before it applies one.

import type Stripe from 'stripe';
import { emitSupersededBillingEvent } from './stripe-webhook-metrics.js';
import { BILLING_IDENTITY_PROJECTION, readSubscription } from './subscription-store.js';

/**
 * Whether the stored row has already moved on from the subscription this event
 * is about.
 *
 * Applying a late cancellation or payment failure would put a paying tenant into
 * grace or past-due on the strength of an event about a subscription that no
 * longer matters. Only a present-and-different id refuses: a row that names no
 * subscription (the pre-activation trial cohort, or a row this event is the
 * first to touch) says nothing about which one is live, so the write proceeds.
 *
 * Only the destructive writers ask. `handleSubscriptionUpdate` is an upsert and
 * keeps last-writer-wins, because an upgrade legitimately arrives under a new id
 * and refusing it as superseded would be the worse failure.
 */
export async function subscriptionSuperseded({
  source,
  userId,
  orgId,
  subscriptionId,
}: {
  /** The webhook event that was about to write, for the log and the metric. */
  source: string;
  userId: string;
  orgId: string | undefined;
  subscriptionId: string | undefined;
}): Promise<boolean> {
  // No org means no row: after the re-key the org id is the key, so there is
  // nothing to compare the event against and nothing the write can reach either.
  if (!subscriptionId || !orgId) return false;
  const stored = await readSubscription(orgId, {
    projectionExpression: BILLING_IDENTITY_PROJECTION,
  });
  const storedId = stored?.subscriptionId;
  if (!storedId || storedId === subscriptionId) return false;

  console.warn('[billing-identity] Skipping a write for a superseded subscription', {
    source,
    userId,
    orgId,
    eventSubscriptionId: subscriptionId,
    storedSubscriptionId: storedId,
  });
  emitSupersededBillingEvent({ source, field: 'subscription' });
  return true;
}

/**
 * Whether the stored row has already moved on from the customer this event is
 * about — the same refusal one identity up. Its caller is the account-deletion
 * trigger, which destroys the whole org: a `customer.deleted` for a customer
 * the account replaced months ago is exactly the event this exists to stop.
 * Only a present-and-different stored id refuses; a row that names no customer
 * cannot answer, and the caller proceeds as before.
 */
export async function customerSuperseded({
  source,
  orgId,
  customerId,
}: {
  /** The webhook event or job path that was about to act, for the log and the metric. */
  source: string;
  orgId: string;
  customerId: string;
}): Promise<boolean> {
  const stored = await readSubscription(orgId, {
    projectionExpression: BILLING_IDENTITY_PROJECTION,
  });
  const storedId = stored?.stripeCustomerId;
  if (!storedId || storedId === customerId) return false;

  console.warn('[billing-identity] Refusing to act on a superseded customer', {
    source,
    orgId,
    eventCustomerId: customerId,
    storedCustomerId: storedId,
  });
  emitSupersededBillingEvent({ source, field: 'customer' });
  return true;
}

/** The subscription an invoice was generated by, when it names one. */
export function invoiceSubscriptionId(invoice: Stripe.Invoice): string | undefined {
  const subscription = invoice.parent?.subscription_details?.subscription;
  if (!subscription) return undefined;
  return typeof subscription === 'string' ? subscription : subscription.id;
}

/**
 * The subscription metadata an invoice carries, when it carries any.
 *
 * Stripe snapshots the subscription's metadata onto the invoice at
 * finalization, so an invoice event can name the org that generated it without
 * a round trip to fetch the subscription back. That makes it the more specific
 * source for `resolveOrgId`, ahead of the customer's own metadata.
 */
export function invoiceSubscriptionMetadata(invoice: Stripe.Invoice): Stripe.Metadata | undefined {
  return invoice.parent?.subscription_details?.metadata ?? undefined;
}
